#!/usr/bin/env bash
# Usage: mangle_cl.sh OUTPUT INPUT1 INPUT2...

output="$1"
echo "// generated by $0" > "${output}"

for input in "${@:2}" ; do
	name=`basename "${input}" .cl`
	echo "const char *${name} = R\"(" >> "${output}"
	${CC:-gcc} -xc -E -nostdinc -D__OPENCL_VERSION__=1 "${input}" >> "${output}"
	echo ")\";" >> "${output}"
done
